apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-be
  template:
    metadata:
      labels:
        app: app-be
    spec:
      containers:
        - name: k8sdemo
          image: duytronguit/k8sdemo
          ports:
            - name: http
              containerPort: 3022
          envFrom:
            - configMapRef:
                name: app-config
# ---
# apiVersion: apps/v1
# kind: Service
# metadata:
#   name: app-be-srv
#   namespace: k8sdemo
# spec:

