name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./Dockerfile --tag duytronguit/k8sdemo
    - name: Get Docker Hub Credentials
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push image
      run: docker push duytronguit/k8sdemo
    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_PAT }}
    - name: Get Cloud (digital-ocean) cluster
      run: doctl kubernetes cluster kubeconfig save k8s
    - name: Get Source
      run: kubectl rollout restart deployment app-be